version: '3.8'

services:
  # 1) EXpress service
  task-service:
    build:
      context: ./
    container_name: "task-management-service"
    ports:
      - "3000:3000" # Host port 3000 -> Container port 3000
    environment:
      PORT: 3000
      DB_URL: mongodb://mongo:27017/task-manager
    depends_on:
      - mongo
    networks:
      - task-management-network

  # 3) MongoDB
  mongo:
    image: mongo:latest
    container_name: task-management-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - task-management-network

volumes:
  mongo_data:

networks:
  task-management-network:
    driver: bridge

